import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex flex-row justify-between items-center bg-[#262626] font-sans text-sm h-[54px] dark:bg-black p-4 text-white z-1">
          <Image
            src="/logoX.svg"
            alt="Logo"
            width={200}
            height={48}
          />
          <div className="absolute left-[35%]">Limited time offer, Buy XTRA WordPress theme only <strong>$39</strong></div>
          <button className="bg-[#82b440] text-[#262626] px-4 py-2 rounded font-[Asap]">Download XTRA Theme</button>
        </header>
        {children}
      </body>
    </html>
  );
}
